import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import babel from "@babel/core";

const root = path.dirname(fileURLToPath(import.meta.url));
const p = (...bits) => path.join(root, ...bits);

/* ------------------------------------------------------------ sections --- */

const NOTES = {
  __preamble__: ["File header", "Imports and the contract. One file on purpose: copy it, then replace the sections marked Replace.", "keep"],
  theme: ["Theme tokens", "Two palettes. Every component reads colour from this object, so brand swapping is a one-object change. The only hard-coded colours are the black and white of the QR plate, which have to stay that way to scan.", "replace"],
  "qr encoder": ["QR encoder", "Vendor code, verified against a reference encoder and round-trip decoded. Already ship a QR library? Delete this block and keep the QrCode signature.", "vendor"],
  money: ["Money and destinations", "Formatting plus parseDestination, your validation surface. This is where a cashtag stops being a cashtag: strip the dollar sign, append the Cash App domain, and it is an ordinary Lightning address from there down.", "replace"],
  "sdk seams": ["SDK seams", "The three calls between this mock and a live integration. The conference build passes a live object here that talks to the Amboss Payments API through our server. Nothing else in the file touches a network.", "seam"],
  state: ["PaymentsProvider", "Shared state and the money mutations. When the api can load state, the server owns the balance and this component stops doing arithmetic. usdPerBtc arrives as a prop and never reaches the screen.", "replace"],
  primitives: ["UI primitives", "Button, Card, Row, Chip, Notice, and the keyframes. Have a design system? Delete this block and map the same props onto your own components.", "replace"],
  "shared pieces": ["Shared pieces", "Countdown, copy button, dollar amount field, and the demo control strip.", "keep"],
  "theme toggle": ["ThemeToggle", "Small enough to inline. Drop it if your host app owns the theme.", "keep"],
  deposit: ["DepositFlow", "Amount, then invoice with QR and countdown, then credited. Seam 1 mints the invoice, seam 2 reports the payment. Expiry and failure both offer a new invoice for the same amount.", "keep"],
  wallet: ["WalletView", "Balance, deposit and cash out, filtered history, detail sheet. Dollars only.", "keep"],
  withdraw: ["WithdrawFlow", "Destination first. An invoice carrying an amount skips amount entry and goes straight to review with the balance check. A cashtag, address, or zero-amount invoice routes through amount entry. Seam 3 sends.", "keep"],
  shell: ["Shell and mount", "The standalone harness. The conference app replaces this with its own three-mode chrome and mounts the same three flows.", "replace"],
};

function buildSections() {
  const SRC = fs.readFileSync(p("src", "AmbossCashierMock.jsx"), "utf8");
  const banner = /\/\*\s-{3,}\s*([a-z][a-z ]*?)\s*-{3,}\s*\*\//g;
  const marks = [];
  let m;
  while ((m = banner.exec(SRC))) marks.push([m.index, m[1]]);

  const chunks = [];
  if (marks.length && marks[0][0] > 0) chunks.push(["__preamble__", SRC.slice(0, marks[0][0])]);
  marks.forEach(([start, name], i) => {
    const end = i + 1 < marks.length ? marks[i + 1][0] : SRC.length;
    chunks.push([name, SRC.slice(start, end)]);
  });

  let line = 1;
  const sections = chunks.map(([name, code]) => {
    const [title, note, kind] = NOTES[name] || [name, "", "keep"];
    const entry = {
      id: name.replace(/[^a-z0-9]+/g, "-"),
      title,
      note,
      kind,
      start: line,
      code,
    };
    line += code.split("\n").length - 1;
    return entry;
  });

  if (sections.map((s) => s.code).join("") !== SRC)
    throw new Error("sections do not reassemble into the source file");

  fs.writeFileSync(
    p("src", "generated-sections.js"),
    "/* Generated by build.mjs. Do not edit. */\n" +
      "export const SECTIONS = " +
      JSON.stringify(sections) +
      ";\n" +
      "export const SOURCE = SECTIONS.map(function (s) { return s.code; }).join('');\n"
  );
  return { sections, lines: SRC.split("\n").length };
}

/* -------------------------------------------------------------- bundle --- */

async function buildBundle() {
  const result = await esbuild.build({
    entryPoints: [p("src", "index.jsx")],
    bundle: true,
    write: false,
    format: "iife",
    target: "es2017",
    jsx: "transform",
    define: { "process.env.NODE_ENV": '"production"' },
    loader: { ".js": "jsx" },
    logLevel: "warning",
  });
  const es2017 = result.outputFiles[0].text;

  /* Down to ES5 so an old iPad can parse it at all. */
  const lowered = babel.transformSync(es2017, {
    babelrc: false,
    configFile: false,
    compact: false,
    presets: [["@babel/preset-env", { targets: { ie: "11" }, bugfixes: true, loose: true }]],
  }).code;

  const min = await esbuild.transform(lowered, { minify: true, target: "es5" });
  return min.code;
}

/* --------------------------------------------------------------- pages --- */

function page(bootstrap, hostConfig) {
  return fs
    .readFileSync(p("src", "page.html"), "utf8")
    .replace("__HOST_CONFIG__", JSON.stringify(hostConfig))
    .replace("__BOOTSTRAP__", bootstrap);
}

const CHECK = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cashier device check</title>
<style>
 body{font:16px -apple-system,Helvetica,Arial,sans-serif;background:#0A1020;color:#E8EEF9;margin:0;padding:20px}
 h1{font-size:19px;margin:0 0 4px} p.sub{color:#8394B1;font-size:13px;margin:0 0 18px}
 table{border-collapse:collapse;width:100%;max-width:640px}
 td{padding:9px 8px;border-bottom:1px solid #22304C;font-size:14px;vertical-align:top}
 td.v{text-align:right;font-weight:700;white-space:nowrap}
 .ok{color:#14C58F} .no{color:#FF6A5E} .meh{color:#FFB020}
 .note{max-width:640px;margin-top:18px;font-size:13px;line-height:1.6;color:#8394B1}
 code{color:#E8EEF9}
</style></head><body>
<h1>Cashier device check</h1>
<p class="sub">Run this on the booth iPad before the doors open.</p>
<table id="t"></table>
<div class="note" id="verdict"></div>
<script>
function row(name, pass, detail, soft) {
  var tr = document.createElement('tr');
  var cls = pass ? 'ok' : (soft ? 'meh' : 'no');
  tr.innerHTML = '<td>' + name + (detail ? '<br><span style="color:#5C6E8D;font-size:12px">' + detail + '</span>' : '') +
    '</td><td class="v ' + cls + '">' + (pass ? 'yes' : 'no') + '</td>';
  document.getElementById('t').appendChild(tr);
  return pass || soft;
}
function supports(prop, value) {
  if (window.CSS && CSS.supports) return CSS.supports(prop, value);
  var el = document.createElement('div');
  try { el.style[prop] = value; return el.style[prop] !== ''; } catch (e) { return false; }
}
var hard = true, soft = true;
hard = row('Promise', typeof Promise === 'function') && hard;
hard = row('CSS grid', supports('display', 'grid')) && hard;
hard = row('Flexbox', supports('display', 'flex')) && hard;
soft = row('Flex gap', supports('gap', '10px'), 'Without it a few rows sit closer together', true) && soft;
soft = row('fetch', typeof fetch === 'function', 'Falls back to XHR', true) && soft;
soft = row('Clipboard API', !!(navigator.clipboard && navigator.clipboard.writeText), 'Falls back to execCommand', true) && soft;
soft = row('Sticky position', supports('position', 'sticky'), '', true) && soft;
row('Screen', true, window.innerWidth + ' x ' + window.innerHeight + ' css px, dpr ' + (window.devicePixelRatio || 1));
row('Browser', true, navigator.userAgent);
var v = document.getElementById('verdict');
v.innerHTML = hard
  ? '<b style="color:#14C58F">Good to go.</b> ' + (soft ? 'Everything supported.' : 'Some cosmetic gaps, listed above in amber. The demo still runs.')
  : '<b style="color:#FF6A5E">This device cannot run the app.</b> Use a newer iPad, or run the demo from a laptop.';
try {
  var x = new XMLHttpRequest();
  x.open('GET', 'healthz', true);
  x.onload = function () { row('Server', x.status === 200, 'healthz says ' + x.responseText.slice(0, 120)); };
  x.onerror = function () { row('Server', false, 'no answer from healthz, offline file only'); };
  x.send();
} catch (e) {}
</script></body></html>`;

/* ---------------------------------------------------------------- main --- */

const { sections, lines } = buildSections();
const bundle = await buildBundle();

fs.mkdirSync(p("public"), { recursive: true });
fs.mkdirSync(p("offline"), { recursive: true });

fs.writeFileSync(p("public", "app.js"), bundle);
fs.writeFileSync(p("public", "index.html"), page('<script src="app.js"></script>', { live: true }));
fs.writeFileSync(p("public", "check.html"), CHECK);
fs.writeFileSync(
  p("offline", "cashier-offline.html"),
  page("<script>" + bundle + "</script>", { live: false })
);

const kb = (n) => Math.round(n / 1024) + " KB";
console.log("sections   ", sections.length, "covering", lines, "lines");
console.log("app.js     ", kb(bundle.length));
console.log("index.html ", kb(fs.statSync(p("public", "index.html")).size));
console.log("offline    ", kb(fs.statSync(p("offline", "cashier-offline.html")).size));
